// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aleksrutins/litelytics/ent/predicate"
	"github.com/aleksrutins/litelytics/ent/site"
	"github.com/aleksrutins/litelytics/ent/visit"
)

// VisitUpdate is the builder for updating Visit entities.
type VisitUpdate struct {
	config
	hooks    []Hook
	mutation *VisitMutation
}

// Where appends a list predicates to the VisitUpdate builder.
func (vu *VisitUpdate) Where(ps ...predicate.Visit) *VisitUpdate {
	vu.mutation.Where(ps...)
	return vu
}

// SetPath sets the "path" field.
func (vu *VisitUpdate) SetPath(s string) *VisitUpdate {
	vu.mutation.SetPath(s)
	return vu
}

// SetReferer sets the "referer" field.
func (vu *VisitUpdate) SetReferer(s string) *VisitUpdate {
	vu.mutation.SetReferer(s)
	return vu
}

// SetTimestamp sets the "timestamp" field.
func (vu *VisitUpdate) SetTimestamp(t time.Time) *VisitUpdate {
	vu.mutation.SetTimestamp(t)
	return vu
}

// SetIP sets the "ip" field.
func (vu *VisitUpdate) SetIP(s string) *VisitUpdate {
	vu.mutation.SetIP(s)
	return vu
}

// SetSiteID sets the "site" edge to the Site entity by ID.
func (vu *VisitUpdate) SetSiteID(id int) *VisitUpdate {
	vu.mutation.SetSiteID(id)
	return vu
}

// SetSite sets the "site" edge to the Site entity.
func (vu *VisitUpdate) SetSite(s *Site) *VisitUpdate {
	return vu.SetSiteID(s.ID)
}

// Mutation returns the VisitMutation object of the builder.
func (vu *VisitUpdate) Mutation() *VisitMutation {
	return vu.mutation
}

// ClearSite clears the "site" edge to the Site entity.
func (vu *VisitUpdate) ClearSite() *VisitUpdate {
	vu.mutation.ClearSite()
	return vu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vu *VisitUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vu.hooks) == 0 {
		if err = vu.check(); err != nil {
			return 0, err
		}
		affected, err = vu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VisitMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vu.check(); err != nil {
				return 0, err
			}
			vu.mutation = mutation
			affected, err = vu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vu.hooks) - 1; i >= 0; i-- {
			if vu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (vu *VisitUpdate) SaveX(ctx context.Context) int {
	affected, err := vu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vu *VisitUpdate) Exec(ctx context.Context) error {
	_, err := vu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vu *VisitUpdate) ExecX(ctx context.Context) {
	if err := vu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vu *VisitUpdate) check() error {
	if _, ok := vu.mutation.SiteID(); vu.mutation.SiteCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Visit.site"`)
	}
	return nil
}

func (vu *VisitUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   visit.Table,
			Columns: visit.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: visit.FieldID,
			},
		},
	}
	if ps := vu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vu.mutation.Path(); ok {
		_spec.SetField(visit.FieldPath, field.TypeString, value)
	}
	if value, ok := vu.mutation.Referer(); ok {
		_spec.SetField(visit.FieldReferer, field.TypeString, value)
	}
	if value, ok := vu.mutation.Timestamp(); ok {
		_spec.SetField(visit.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := vu.mutation.IP(); ok {
		_spec.SetField(visit.FieldIP, field.TypeString, value)
	}
	if vu.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visit.SiteTable,
			Columns: []string{visit.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: site.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visit.SiteTable,
			Columns: []string{visit.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: site.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{visit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// VisitUpdateOne is the builder for updating a single Visit entity.
type VisitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VisitMutation
}

// SetPath sets the "path" field.
func (vuo *VisitUpdateOne) SetPath(s string) *VisitUpdateOne {
	vuo.mutation.SetPath(s)
	return vuo
}

// SetReferer sets the "referer" field.
func (vuo *VisitUpdateOne) SetReferer(s string) *VisitUpdateOne {
	vuo.mutation.SetReferer(s)
	return vuo
}

// SetTimestamp sets the "timestamp" field.
func (vuo *VisitUpdateOne) SetTimestamp(t time.Time) *VisitUpdateOne {
	vuo.mutation.SetTimestamp(t)
	return vuo
}

// SetIP sets the "ip" field.
func (vuo *VisitUpdateOne) SetIP(s string) *VisitUpdateOne {
	vuo.mutation.SetIP(s)
	return vuo
}

// SetSiteID sets the "site" edge to the Site entity by ID.
func (vuo *VisitUpdateOne) SetSiteID(id int) *VisitUpdateOne {
	vuo.mutation.SetSiteID(id)
	return vuo
}

// SetSite sets the "site" edge to the Site entity.
func (vuo *VisitUpdateOne) SetSite(s *Site) *VisitUpdateOne {
	return vuo.SetSiteID(s.ID)
}

// Mutation returns the VisitMutation object of the builder.
func (vuo *VisitUpdateOne) Mutation() *VisitMutation {
	return vuo.mutation
}

// ClearSite clears the "site" edge to the Site entity.
func (vuo *VisitUpdateOne) ClearSite() *VisitUpdateOne {
	vuo.mutation.ClearSite()
	return vuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vuo *VisitUpdateOne) Select(field string, fields ...string) *VisitUpdateOne {
	vuo.fields = append([]string{field}, fields...)
	return vuo
}

// Save executes the query and returns the updated Visit entity.
func (vuo *VisitUpdateOne) Save(ctx context.Context) (*Visit, error) {
	var (
		err  error
		node *Visit
	)
	if len(vuo.hooks) == 0 {
		if err = vuo.check(); err != nil {
			return nil, err
		}
		node, err = vuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VisitMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vuo.check(); err != nil {
				return nil, err
			}
			vuo.mutation = mutation
			node, err = vuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(vuo.hooks) - 1; i >= 0; i-- {
			if vuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, vuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Visit)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from VisitMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (vuo *VisitUpdateOne) SaveX(ctx context.Context) *Visit {
	node, err := vuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vuo *VisitUpdateOne) Exec(ctx context.Context) error {
	_, err := vuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuo *VisitUpdateOne) ExecX(ctx context.Context) {
	if err := vuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vuo *VisitUpdateOne) check() error {
	if _, ok := vuo.mutation.SiteID(); vuo.mutation.SiteCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Visit.site"`)
	}
	return nil
}

func (vuo *VisitUpdateOne) sqlSave(ctx context.Context) (_node *Visit, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   visit.Table,
			Columns: visit.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: visit.FieldID,
			},
		},
	}
	id, ok := vuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Visit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, visit.FieldID)
		for _, f := range fields {
			if !visit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != visit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vuo.mutation.Path(); ok {
		_spec.SetField(visit.FieldPath, field.TypeString, value)
	}
	if value, ok := vuo.mutation.Referer(); ok {
		_spec.SetField(visit.FieldReferer, field.TypeString, value)
	}
	if value, ok := vuo.mutation.Timestamp(); ok {
		_spec.SetField(visit.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := vuo.mutation.IP(); ok {
		_spec.SetField(visit.FieldIP, field.TypeString, value)
	}
	if vuo.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visit.SiteTable,
			Columns: []string{visit.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: site.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visit.SiteTable,
			Columns: []string{visit.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: site.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Visit{config: vuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{visit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
