// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Visit is the predicate function for visit builders.
type Visit func(*sql.Selector)
